version: '3'
services:
  web:
    build: .
    command: npm run start-server
    volumes:
      - .:/home/node
    ports:
      - "5000:8080"
    environment:
      - NODE_ENV=production
      - SERVER_ADR=filewire.io